title: "わかるはたのしい"
email: "ijkfunmath@gmail.com"
description: >-
  これらのアプリで、楽しみながら学習の新たな扉を開いてみてください！
baseurl: ""
url: "https://htojo2008.github.io"
twitter_username: "axljoe2001"
github_username:  "htojo2008"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# ヘッダーメニューの表示順序を指定
# ここに記載したファイルが上から順にメニューに並びます
header_pages:
  - index.markdown
  - goi.markdown
  - ijkFunMath.markdown
  - PrivacyPolicy.markdown
  - terms.markdown
  - about.markdown

# 除外設定
exclude:
  - _history
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - _config_bkup.yml
  - Terms_of_Service/ # 変換前のHTMLフォルダは除外を推奨